# Generated by Django 5.0.1 on 2025-06-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webback', '0002_utilisateur_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('codePostal', models.AutoField(primary_key=True, serialize=False)),
                ('nomVille', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'db_table': 'ville',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='numCodePostal',
            field=models.ForeignKey(db_column='codePostal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='webback.ville'),
        ),
    ]
