# Generated by Django 5.0.1 on 2025-06-24 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webback', '0003_ville_client_numcodepostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisExcpedition',
            fields=[
                ('numExp', models.AutoField(primary_key=True, serialize=False)),
                ('nomChauffeur', models.CharField(max_length=100)),
                ('prenomChauffeur', models.CharField(max_length=100, null=True)),
                ('telChauffeur', models.CharField(max_length=17, null=True)),
                ('modeLivraison', models.CharField(max_length=100)),
                ('immatVehicule', models.CharField(max_length=40)),
                ('coopVehicule', models.CharField(max_length=50)),
                ('dateLivraison', models.DateTimeField(default=django.utils.timezone.now)),
                ('numCommande', models.ForeignKey(db_column='numCommande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='webback.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'livraison',
            },
        ),
    ]
